version: '3'
services:

  postgres:
    image: postgres:13.3-alpine
    container_name: container-biblioteca_cdd
    environment:
      - POSTGRES_DB=biblioteca_cdd
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "postgres-volume-db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

volumes:
  postgres-volume-db: